apiVersion: v1
kind: Service
metadata:
  name: orders-service
  namespace: orders
spec:
  selector:
    app: orders-microservice
  ports:
    - port: 80
      targetPort: 5050
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: orders-service-internal
  namespace: orders
spec:
  selector:
    app: orders-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5050
  type: ClusterIP